services:
  backend:
    build: ./backend
    container_name: shopverse-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    networks:
      - shopverse-net

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://13.53.172.109:5000
    container_name: shopverse-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - shopverse-net

networks:
  shopverse-net:
    driver: bridge
