name: Explore Runner

on:
  push:

jobs:
  explore:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Current Directory
        run: pwd

      - name: List Files
        run: ls -la

      - name: Current User
        run: whoami

      - name: Show Date
        run: date

      - name: Docker Version
        run: docker --version
